# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
      TrajetsBundle\Entity\Utilisateur: sha512

  role_hierarchy:
      ROLE_COLLECTEUR: ROLE_USER
      ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
      utilisateurs:
            id: fos_user.user_provider.username_email

  firewalls:
      dev:
        pattern: ^/(_(profiler|wdt|console)|css|images|js)/
        security: false
      main:
        pattern:   ^/
        anonymous: true
        provider: utilisateurs
        form_login:
          login_path: fos_user_security_login
          check_path: fos_user_security_check
          default_target_path: trajets_homepage
        logout:
          path: fos_user_security_logout
          target: /login
        remember_me:
          secret: "%secret%"

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, role: ROLE_USER }
